// ── Stage 5: Export — product data artifacts ──────────────────────────────────

import { ExportArtifacts, SpecDocument } from "@/lib/types";

function csvCell(v: string): string {
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function attr(p: { attributes: { name: string; value: string }[] }, name: string): string {
  return p.attributes.find((a) => a.name.toLowerCase().startsWith(name.toLowerCase()))?.value ?? "";
}

export function renderMarkdown(spec: Omit<SpecDocument, "exports">): string {
  const lines: string[] = [];
  const date = new Date(spec.createdAt).toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });

  lines.push(`# ${spec.title}`);
  lines.push("");
  lines.push(
    `> Organized by **SpecForge AI** · ${date} · ${spec.mode === "ai" ? `live AI (${spec.model ?? "ai"})` : "built-in parser"} · **${spec.products.length} products** · ${spec.quality.attributeCount} attribute values · quality **${spec.quality.score}/100**`
  );
  if (spec.modeNote) lines.push(`> _${spec.modeNote}_`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| # | Product | Brand | Part number | Attributes |");
  lines.push("|---|---------|-------|-------------|------------|");
  spec.products.forEach((p, i) => {
    lines.push(
      `| ${i + 1} | ${p.name.replace(/\|/g, "\\|")} | ${p.brand ?? "—"} | ${p.partNumber ?? "—"} | ${p.attributes.length} |`
    );
  });
  lines.push("");

  spec.products.forEach((p, i) => {
    lines.push(`## ${i + 1}. ${p.name}`);
    lines.push("");
    if (p.brand || p.category || p.partNumber) {
      const bits = [p.brand, p.category, p.partNumber].filter(Boolean);
      lines.push(`**${bits.join(" · ")}**`);
      lines.push("");
    }
    if (p.description) {
      lines.push(p.description);
      lines.push("");
    }
    if (p.attributes.length) {
      lines.push("| Attribute | Value |");
      lines.push("|-----------|-------|");
      for (const a of p.attributes) {
        lines.push(`| ${a.name.replace(/\|/g, "\\|")} | ${a.value.replace(/\|/g, "\\|")} |`);
      }
      lines.push("");
    }
    if (p.keyFeatures?.length) {
      lines.push("**Key features**");
      lines.push("");
      for (const f of p.keyFeatures) lines.push(`- ${f}`);
      lines.push("");
    }
    if (p.useCases?.length) {
      lines.push("**Use cases**");
      lines.push("");
      for (const u of p.useCases) lines.push(`- ${u}`);
      lines.push("");
    }
    if (i < spec.products.length - 1) {
      lines.push("---");
      lines.push("");
    }
  });

  lines.push("---");
  lines.push("");
  lines.push("_Generated by SpecForge AI — messy documents in, organized product data out._");
  return lines.join("\n");
}

export function renderCsv(spec: Omit<SpecDocument, "exports">): string {
  const header = ["id", "name", "brand", "category", "part_number", "description", "attributes", "key_features", "use_cases"];
  const rows = spec.products.map((p) =>
    [
      p.id,
      p.name,
      p.brand ?? "",
      p.category ?? "",
      p.partNumber ?? "",
      p.description ?? "",
      p.attributes.map((a) => `${a.name}: ${a.value}`).join(" | "),
      (p.keyFeatures ?? []).join(" | "),
      (p.useCases ?? []).join(" | "),
    ]
      .map(csvCell)
      .join(",")
  );
  return [header.join(","), ...rows].join("\n");
}

export function renderJson(spec: Omit<SpecDocument, "exports">): string {
  return JSON.stringify(
    {
      title: spec.title,
      createdAt: spec.createdAt,
      generator: { mode: spec.mode, model: spec.model ?? null, note: spec.modeNote ?? null },
      stats: {
        products: spec.products.length,
        attributeValues: spec.quality.attributeCount,
        qualityScore: spec.quality.score,
      },
      quality: spec.quality.findings,
      products: spec.products,
    },
    null,
    2
  );
}

export function renderExports(spec: Omit<SpecDocument, "exports">): ExportArtifacts {
  return {
    markdown: renderMarkdown(spec),
    json: renderJson(spec),
    csv: renderCsv(spec),
  };
}
